#+title: README
#+date: 2022-03-23 16:18 Wed
#+author: Gary Klimowicz


* Overview
This set of directories and files mirrors the contents of
[[https://j3-fortran.org]], maintained by Steve Lionel, the ISO WG5
convenor. This web site is the system of record for papers presented and
discussed by the INCITS Fortran and ISO WG5 Fortran standards groups.

The j3-fortran web site organizes papers by year. The ~years~ directory
holds the papers for each 4-digit year. (j3-fortran.org uses 2-year
dates, which has unfortunate grep behavior, with papers from the 1980's
and 1990's listed after papers form 2000 and beyond.)

j3-fortran.org also indexes papers by meeting. The ~meetings~ directory
contains a directory for each meeting (padded to 3 digits). The
documents for each meeting are symlinks to the documents in the ~years~
directory.

Since each paper has a unique name, the ~papers~ directory has one symlink
into ~years~ for each paper. This flattens the hierarchies in ~years~ and
~meetings~ to make lookup simpler for individual papers. (Note that the
j3-fortran.org web site indexes some documents, such as minutes, in
multiple places. These give the appearance of multiple versions of
documents with the same name, but in every case they turn out to be
identical.)


* bin commands
There are commands in the ~bin~ directory to maintain this repository.

** ~bin/get-docs-for-meeting~
Given a meeting number ~nnn~ (or an entry in the ~meetings~ directory), pull
all the meeting files, and place the real files in the ~years~ directory,
and a link to that file in the ~meetings/nnn~ and ~papers~ directory.

By default, the command cleans up the text in the ~.txt~ files to remove
unnecessary inconsistencies. The possible cleanups are:

    - Change DOS CRLF line endings to Unix line endings (LF).
    - Change Mac CR line endings to Unix line endings (LF).
    - Delete DOS end-of-file (^Z) markers.
    - Delete NUL (<00>) characters.
    - Change ^R to double quotes ("); this is an artifact of some old editor.
    - Change ^S to open single quote (`); another editor artifact.
    - Change ^T to close single quotes('); another old editor artifact.
    - Change extended ASCII punctuation characters to ASCII characters.
    - Change <FF>2D to plus sign (+); I don't know where this came from.

#+begin_src sh
bin/get-docs-for-meeting 226           # Fetch all meeting 226 documents
bin/get-docs-for-meeting meetings/226  # This does the same thing

bin/get-docs-for-meting meetings/*     # Fetch documents for all meetings
#+end_src

Useful options:
    - ~-v~ :: Be verbose about the actions taken.
    - ~-vv~ :: Add debug output tn the verbose output.
    - ~-r~ :: Don't clean up the text beyond line ending regularization.

** ~bin/cleanup-text~
This filter cleans up text as described above. It can take the ~-r~ option
to limit the cleanup, which can be useful for explaining to Steve Lionel
oddities found in the documents.

** ~bin/wheres~
Given a document prefix, identify all the locations of the document.

#+begin_example
$ bin/wheres S8
S8:
  S8.102.pdf	meetings/102/S8.102.pdf
  S8.102.pdf	papers/S8.102.pdf
  S8.102.pdf	years/1986/S8.102.pdf
  S8.103.pdf	meetings/103/S8.103.pdf
  S8.103.pdf	papers/S8.103.pdf
  S8.103.pdf	years/1987/S8.103.pdf
  S8.104.pdf	meetings/104/S8.104.pdf
  S8.104.pdf	papers/S8.104.pdf
  S8.104.pdf	years/1987/S8.104.pdf
  S8.111.pdf	meetings/111/S8.111.pdf
  S8.111.pdf	papers/S8.111.pdf
  S8.111.pdf	years/1989/S8.111.pdf
  S8.114.pdf	meetings/114/S8.114.pdf
  S8.114.pdf	papers/S8.114.pdf
  S8.114.pdf	years/1990/S8.114.pdf
  S8.115.pdf	meetings/115/S8.115.pdf
  S8.115.pdf	papers/S8.115.pdf
  S8.115.pdf	years/1990/S8.115.pdf
  S8.99.pdf	meetings/099/S8.99.pdf
  S8.99.pdf	papers/S8.99.pdf
  S8.99.pdf	years/1986/S8.99.pdf
#+end_example

#+begin_example
$ bin/wheres 22-124
22-124:
  22-124.txt	meetings/226/22-124.txt
  22-124.txt	papers/22-124.txt
  22-124.txt	years/2022/22-124.txt
  22-124r1.txt	meetings/226/22-124r1.txt
  22-124r1.txt	papers/22-124r1.txt
  22-124r1.txt	years/2022/22-124r1.txt
  22-124r2.txt	meetings/226/22-124r2.txt
  22-124r2.txt	papers/22-124r2.txt
  22-124r2.txt	years/2022/22-124r2.txt
#+end_example

** ~bin/make-index~
Creates the ~INDEX~ file used by ~bin/wheres~. For each file, it contains
    - The file's base name (e.g., ~00-000.txt~)
    - The file's line count if it is a ~.txt~ file; otherwise ~n/a~
    - The file's md5 hash
    - A location in the ~meetings~, ~papers~, or ~years~ directory
